# -*- coding: utf-8 -*-
"""Text generation P-1,2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DSJpQVpanUF2NS6QdOIao-amH1B2BxhM
"""

import torch
!pip install transformers torch
from transformers import pipeline
generator =pipeline(
    "text-generation",
    model="gpt2"
)
prompt="Artificial intelligence in finance will"
result=generator(prompt,max_length=50,num_return_sequences=1)
print("AI generated text:")
print(result[0]["generated_text"])



from sentence_transformers import SentenceTransformer, util

# Load model
model = SentenceTransformer('all-MiniLM-L6-v2')

# Input texts
text1 = input("Enter Text 1: ")
text2 = input("Enter Text 2: ")

# Encode texts
embedding1 = model.encode(text1, convert_to_tensor=True)
embedding2 = model.encode(text2, convert_to_tensor=True)

# Cosine similarity
similarity = util.cos_sim(embedding1, embedding2)

score = float(similarity[0][0])

print("\nSimilarity Score:", round(score, 2))

# Similarity level
if score > 0.75:
    print("Similarity Level: High")
elif score > 0.40:
    print("Similarity Level: Medium")
else:
    print("Similarity Level: Low")

